/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.GestorUsuario;


/**
 *
 * @author Alfredo
 */
public class IU_CREARUSUARIO extends javax.swing.JFrame {

    /**
     * Creates new form IU_Administrativo
     */
    public IU_CREARUSUARIO() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        registrado = new javax.swing.JLabel();
        jButtonCrearUsuario = new javax.swing.JButton();
        jLabelPass = new javax.swing.JLabel();
        jTextFieldpass = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jlabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 70, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 530, 30));

        jLabelApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos:");
        getContentPane().add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jTextFieldApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldApellidos.setToolTipText("");
        getContentPane().add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 530, 30));

        jLabelCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo:");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 80, 30));

        registrado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrado.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 330, 30));

        jButtonCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCrearUsuario.setText("Crear Usuario");
        jButtonCrearUsuario.setToolTipText("");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jLabelPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass.setText("Password:");
        getContentPane().add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 80, -1));

        jTextFieldpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 530, 30));

        jButtonLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLimpiar.setText("Limpiar Datos");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 140, -1));

        jTextFieldLogin.setToolTipText("");
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 530, 30));

        jTextFieldCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 530, 30));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("Login:");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 80, 20));

        jlabelfondo.setBackground(new java.awt.Color(255, 255, 255));
        jlabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jlabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        // TODO add your handling code here:
        
        try{
                //registrado.setText("");
                String correo= jTextFieldCorreo.getText();
                String login= jTextFieldLogin.getText();
                String password= jTextFieldpass.getText();
         
         
          boolean autenticar1=GestorUsuario.crearUsuario(jTextFieldNombre.getText(),jTextFieldApellidos.getText(),login,password,correo,"usuario");
                
		if (autenticar1){
		                      
                    registrado.setText("Usuario registrado");
                    IU_LOGIN frame=new IU_LOGIN();
                    frame.setVisible(true);
                    this.setVisible(false);
                    
			}
		    else{
		                                 
                         registrado.setText("Nombre Usuario de cliente ya existe"); 
                         jTextFieldNombre.setText("");
                         jTextFieldApellidos.setText("");
                         jTextFieldpass.setText("");
                         jTextFieldLogin.setText("");
                         jTextFieldCorreo.setText("");
                         
			} 
					
		}catch (Exception e){
		     e.printStackTrace();						
		    }//fin catch
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldApellidos.setText("");
        jTextFieldNombre.setText("");
        jTextFieldpass.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldLogin.setText("");
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_CREARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_CREARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_CREARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_CREARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_CREARUSUARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldpass;
    private javax.swing.JLabel jlabelfondo;
    private javax.swing.JLabel registrado;
    // End of variables declaration//GEN-END:variables
}
