/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import javax.swing.JTextField;
import javax.swing.JButton;

import java.awt.Color;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextPane;

import Dominio.GestorUsuario;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Component;

/**
 *
 * @author Alfredo
 */
public class IU_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form IU_Login
     */
    public IU_LOGIN() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelUsuario.setAlignmentX(Component.RIGHT_ALIGNMENT);
        jLabelPasword = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        registrado = new javax.swing.JLabel();
        jButtonSesion = new javax.swing.JButton();
        jPass = new javax.swing.JPasswordField();
        jLabelFondo = new javax.swing.JLabel();
        jButtonCrear= new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 80, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User.png"))); // NOI18N
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabelUsuario.setBackground(new java.awt.Color(51, 0, 102));
        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 90, 30));

        jLabelPasword.setBackground(new java.awt.Color(51, 0, 102));
        jLabelPasword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPasword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasword.setText("Password:");
        getContentPane().add(jLabelPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 30));

        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 260, 30));

        registrado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrado.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 230, 30));

        jButtonSesion.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSesion.setText("Iniciar Sesión");
        jButtonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSesionActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButtonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 470, -1, -1));
        
        jButtonCrear.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCrear.setText("Crear Usuario");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        jPass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 421, 260, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSesionActionPerformed
        // TODO add your handling code here:
        
	    try{
                registrado.setText("");
                char[] arrayC = jPass.getPassword();
                String pass = new String(arrayC);
                String tipo=null;
                boolean autenticar1=GestorUsuario.login(jTextFieldUser.getText(), pass);
                
                if (autenticar1){
		                      
                    registrado.setText("Registrado");
                    tipo=GestorUsuario.tipo(jTextFieldUser.getText(), pass);
                    
                    if(tipo.equals("admin")){
                        
                        IU_ADMINISTRADOR frame = new IU_ADMINISTRADOR();
                       // frame.setVisible(true);
                        //frame.jLabelNusario.setText(jTextFieldUser.getText());
                        this.setVisible(false);}
                    if(tipo.equals("usuario")){
                        IU_USUARIO frame2 = new IU_USUARIO();                    
                        //frame2.setVisible(true);
                        //frame2.jLabelNusario.setText(jTextFieldUser.getText());
                        this.setVisible(false);}
                    
                }
                else{
		                                 
                         registrado.setText("Usuario o contraseña incorrecta");
                         jPass.setText("");
                         jTextFieldUser.setText("");
                	} 
					
		}catch (Exception e){
		     e.printStackTrace();						
		    }//fin catch
         
         
        
    }//GEN-LAST:event_jButtonSesionActionPerformed
    
    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSesionActionPerformed
        // TODO add your handling code here:
        
	    try{
	    	IU_CREARUSUARIO frame =new IU_CREARUSUARIO();
	    	frame.setVisible(true);
	    	this.setVisible(false);
                
					
		}catch (Exception e){
		     e.printStackTrace();						
		    }//fin catch
         
         
        
    }//GEN-LAST:event_jButtonSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IU_LOGIN().setVisible(true);
		    } catch (Exception e) {
		        e.printStackTrace();
		        }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSesion;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelPasword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPass;
    public static javax.swing.JTextField jTextFieldUser;
    private javax.swing.JLabel registrado;
    // End of variables declaration//GEN-END:variables
}
